// Generated by CoffeeScript 1.9.0
/*
/// Description: This Javascript to keep the session alive as long as the user keeps the browser open with BIS.
/// History:
/// -------------------------------------------------------------------------------
/// Date:               Name                    Description
/// --------------------------------------------------------------------------------
/// 7/10/2015           simpsong                Intial Creation - Run every (session Timeout -1) minutes - to ping server via ajax.
///                                             This JS is loaded from Master page after user is authenticated.
*/

SessionKeepAlive =
{
    delay: 10000,
    url: undefined,
    run: function () {
        if (this.url) {
            $.get(this.url + "?d=" + escape(new Date().getTime()));
            setTimeout("SessionKeepAlive.run()", this.delay);
        }
    },
    start: function (delay, url) {
        // Set ajax timeout to 2 seconds
        $.ajaxSetup({ timeout: 2000 });
        
        // Convert delay to millis
        this.delay = parseInt(delay) * 60000;
        this.url = url;
        setTimeout("SessionKeepAlive.run()", this.delay);
    }
};